# Generated by Django 3.0 on 2022-04-12 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_book_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
