# Generated by Django 3.0 on 2022-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220412_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
