# Generated by Django 3.0 on 2022-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('1', 'Science'), ('2', 'Poetry'), ('3', 'Art'), ('4', 'Philosophy')], max_length=80),
        ),
    ]
