# Generated by Django 3.0 on 2022-04-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220412_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Science'), ('2', 'Poetry'), ('3', 'Art'), ('4', 'Philosophy')], max_length=80, null=True),
        ),
    ]
